# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"func1": "06_main.ipynb",
         "func2": "06_main.ipynb",
         "Class1": "06_main.ipynb"}

modules = ["load.py",
           "preprocess.py",
           "build_features.py",
           "fit.py",
           "transform.py",
           "validate.py",
           "main.py"]

doc_url = "https://{user} #<-- should be a valid git username otherwise doc_host will crash.github.io/{repo_name}/src/"

git_url = "https://github.com/{user} #<-- should be a valid git username otherwise doc_host will crash/src/tree/{branch}/"

def custom_doc_links(name): return None
